config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :pics do
  	resources :comments
  	member do
  		put "like", to: "pics#upvote"
  	end
  end
  root "pics#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :pic
  belongs_to :user
end

app/models/pic.rb
class Pic < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
	has_many :comments, dependent: :destroy

	has_attached_file :image, styles: { medium: "300x300>"}
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

    def self.search(search)
    	if search
    		where(["title LIKE ?","%#{search}%"])
    	else
    		all
    	end
    end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :pics
	has_many :comments, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_comment, only:[:show, :edit, :update, :destroy]
	before_action :set_pic
	before_action :authenticate_user!


	def create
		@comment = Comment.new(comment_params)
		@comment.user_id = current_user.id
		@comment.pic_id = @pic.id
		if @comment.save
		   redirect_to pic_path(@pic)
		else
			render 'new'
		end
	end

	def index
		@comments = Comment.all	
	end

	def show
	end

	def new
		@comment = Comment.new	
	end


	def destroy
		@comment.destroy
		redirect_to pic_path(@pic)
	end

	def update
		@comment.update(comment_params)
		redirect_to pic_path(@pic)
	end


	private 
	def comment_params
		params.require(:comment).permit(:content)	
	end

	def set_comment
		@comment = Comment.find(params[:id])
	end

	def set_pic
		@pic = Pic.find(params[:pic_id])
	end
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
before_action :find_pic, only: [:show, :edit, :update, :destroy, :upvote]
before_action :authenticate_user!, except: [:index, :show]
	def index
		@pics = Pic.all.order("Created_at DESC")
		@pics = Pic.search(params[:search])
	end

	def show
		@comments = Comment.where(pic_id: @pic.id).order("created_at DESC")
	end

	def new
		@pic = current_user.pics.build
	end

	def create
		@pic = current_user.pics.build(pic_params)

		if @pic.save
			redirect_to @pic, notice: "Yessss!!!!! It was posted!"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @pic.update(pic_params)
			redirect_to @pic, notice: "Congrats! Pic was Updated!"
		else 
			render 'edit'
		end
	end

	def destroy
		@pic.destroy
		redirect_to root_path
	end

	def upvote
		@pic.upvote_by current_user
		redirect_to :back
	end

	private 

	def pic_params
		params.require(:pic).permit(:title, :description, :image)
	end

	def find_pic
		@pic = Pic.find(params[:id])
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/comments/_comment.html.erb
<div class="col-md-6.col-md-offset-3">
  <div class="panel.panel-default">
    <div class="panel-footer">
      <div class="row">
        <div class="col-md-6">
          <div class="btn-group.pull-right">
            <% if @comments.blank? %>
            	<h3>No Reviews just yet, would you like to add first!</h3>
            <% else %>
            	<% @comments.each do |comment| %>
            	  <div class="comments">
            	  	<p> <%= comment.content %></p>
                  <p> By <%= comment.user.email %> </p>
                  <% if user_signed_in? &&current_user.id == @pic.user_id %>
                    <%= link_to "Delete Comment", [comment.pic, comment] , method: :delete,class: "btn btn-danger" %>
                  <% end %>
            	  </div>
            	<% end %>
            	<% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="col-md-6.col-md-offset-3">
  <div class="panel.panel-default">
    <div class="panel-footer">
      <div class="row">
        <div class="col-md-6">
          <div class="btn-group.pull-right">
            <%= simple_form_for([@pic, @pic.comments.build]) do |f| %>
              <div class="form-group">
                <%= f.label :Comment %>
                <%= f.text_field :content, required: true, class: "form-control" %>
              </div>
              <div class="form-group">
                  <%= f.button :submit, "Comment", class: "btn btn-info" %>
              </div>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
        

app/views/comments/_search.html.erb
<%= form_tag pics_path, :method => 'get' do %>
<%= text_field_tag :search, params[:search] %>
	<%= submit_tag "Search" %>
<% end %>

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Instagram
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  %nav.navbar.navbar-inverse
    .container
      .navbar-brand= link_to "Instagram", root_path
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Gram It", new_pic_path
          %li= link_to "Settings", edit_user_registration_path
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete
          = render 'comments/search'
      - else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Join", new_user_registration_path
          %li= link_to "Log In", new_user_session_path

  .container
    -flash.each do |name, msg|
      =content_tag :div, msg, class: "alert alert-info"

    = yield

app/views/pics/_form.html.haml
= simple_form_for @pic, html: { multipart: true} do |f|
	- if @pic.errors.any?
		#errors
			%h2
			= pluralize(@pic.errors.count, "error")
			prevented this Pic from saving
			%ul
				- @pic.errors.full_messages.each do |msg|
					%li = msg

	.form-group
		= f.input :image, input_html: { class: 'form-control'}
	.form-group
		= f.input :title, input_html: { class: 'form-control'}
	.form-group   
		= f.input :description, input_html: { class: 'form-control'} 
		
	= f.button :submit, class: "btn btn-info"
 

app/views/pics/edit.html.haml
#edit_page.col-md-8.col-md-offset-2
  .row
    .panel.panel-default
      .panel-heading
        %h1 Fix Pic
      .panel-body
        .current_image
          %strong.center Right Now
          =image_tag @pic.image.url(:medium)
        = render 'form'

app/views/pics/index.html.haml
.col-md-12
  #pics.transitions-enabled
    - @pics.each do |pic|
      .box.panel.panel-default
        = link_to (image_tag pic.image.url), pic
        %h2= link_to pic.title, pic
        %p= pic.user.email
        = render 'comments/comment'

app/views/pics/new.html.haml
.col-md-8.col-md-offset-2
  .row
    .panel.panel-default
      .panel-heading
        %h1 Post Pic
      .panel-body
        = render 'form'

app/views/pics/show.html.haml
#pic_show.row
  .col-md-6.col-md-offset-3
    .panel.panel-default
      .panel.heading.pic_image
        = image_tag @pic.image.url
      .panel-body
        %h1= @pic.title
        %p= @pic.description
    
      .panel-footer
        .row
          .col-md-6
            %p.user 
              by
              = @pic.user.email


          .col.md-6
            .btn-group.pull-right
              = link_to like_pic_path(@pic), method: :put, class: "btn btn-default" do
                %span.glyphicon.glyphicon-thumbs-up
                =@pic.get_upvotes.size
              -if user_signed_in?
                - if @pic.user_id == current_user.id
                  = link_to "Fix Pic", edit_pic_path, class: "btn btn-info"
                  = link_to "Delete", pic_path, method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-danger"
      = render 'comments/comment'
      = render 'comments/form'